name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqlserver
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"  # Password should be same as what is set for SQL Server
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqlserver
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqlserver:
        container_name: "sqlserver"
        image: "mcr.microsoft.com/mssql/server:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqlserver"
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: "${SQL_PASSWORD}" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16

networks:
  sb-emulator:
